# Generated by Django 2.2.3 on 2019-07-01 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('graduates', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='graduate',
            name='year',
            field=models.ForeignKey(default=2019, on_delete=django.db.models.deletion.CASCADE, to='graduates.Class'),
            preserve_default=False,
        ),
    ]
