# Generated by Django 2.2.3 on 2019-07-02 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graduates', '0002_auto_20190701_2316'),
    ]

    operations = [
        migrations.RenameField(
            model_name='graduate',
            old_name='name',
            new_name='name_he',
        ),
        migrations.AddField(
            model_name='graduate',
            name='bezalel_catalog',
            field=models.CharField(default='', max_length=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='graduate',
            name='email',
            field=models.CharField(default='', max_length=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='graduate',
            name='instagram',
            field=models.CharField(default='', max_length=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='graduate',
            name='name_ar',
            field=models.CharField(default='', max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='graduate',
            name='name_en',
            field=models.CharField(default='', max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='graduate',
            name='personal_website',
            field=models.CharField(default='', max_length=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='graduate',
            name='project_title_ar',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='graduate',
            name='project_title_en',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='graduate',
            name='project_title_he',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
