# Generated by Django 2.2.3 on 2019-07-03 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graduates', '0003_auto_20190702_2204'),
    ]

    operations = [
        migrations.AddField(
            model_name='graduate',
            name='image_0',
            field=models.ImageField(default='', upload_to=''),
            preserve_default=False,
        ),
    ]
