# Generated by Django 2.2.3 on 2019-07-10 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graduates', '0005_auto_20190710_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graduate',
            name='bezalel_catalog',
            field=models.CharField(default='', max_length=60),
        ),
        migrations.AlterField(
            model_name='graduate',
            name='email',
            field=models.CharField(default='', max_length=60),
        ),
        migrations.AlterField(
            model_name='graduate',
            name='instagram',
            field=models.CharField(default='', max_length=60),
        ),
        migrations.AlterField(
            model_name='graduate',
            name='name_ar',
            field=models.CharField(default='', max_length=35),
        ),
        migrations.AlterField(
            model_name='graduate',
            name='name_en',
            field=models.CharField(default='', max_length=35),
        ),
        migrations.AlterField(
            model_name='graduate',
            name='name_he',
            field=models.CharField(default='', max_length=35),
        ),
        migrations.AlterField(
            model_name='graduate',
            name='personal_website',
            field=models.CharField(default='', max_length=60),
        ),
        migrations.AlterField(
            model_name='graduate',
            name='project_title_ar',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='graduate',
            name='project_title_en',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='graduate',
            name='project_title_he',
            field=models.CharField(default='', max_length=100),
        ),
    ]
