# Generated by Django 2.2.3 on 2019-07-10 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graduates', '0006_auto_20190710_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graduate',
            name='bezalel_catalog',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
        migrations.AlterField(
            model_name='graduate',
            name='email',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
        migrations.AlterField(
            model_name='graduate',
            name='instagram',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
        migrations.AlterField(
            model_name='graduate',
            name='name_ar',
            field=models.CharField(blank=True, default='', max_length=35),
        ),
        migrations.AlterField(
            model_name='graduate',
            name='name_en',
            field=models.CharField(blank=True, default='', max_length=35),
        ),
        migrations.AlterField(
            model_name='graduate',
            name='name_he',
            field=models.CharField(blank=True, default='', max_length=35),
        ),
        migrations.AlterField(
            model_name='graduate',
            name='personal_website',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
        migrations.AlterField(
            model_name='graduate',
            name='project_title_ar',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='graduate',
            name='project_title_en',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='graduate',
            name='project_title_he',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
